# Basic
title: Octan3
subtitle: A LIFE PLAYER
description: Looking back, shyness or unbearable?
creator: <a href="http://duola-li.github.io">Octan3</a>

url: "http://duola-li.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: 个人博客

# Navigation buttons in the front page.
nav:
    - {title: Note, description: CSDN博客, url: 'https://blog.csdn.net/Monster_li57'}
    - {title: Picture, description: 收藏的一些图片, url: 'https://img.liyue.site'}
    # - {title: bzoj-data, description: bzoj数据下载, url: 'https://bzoj.liyue.site'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: Octan3
    zhihu: li-xiao-guai-41
    github: Duola-li
    # gplus: 107108267983477358170
    mail: octan3@qq.com

# Google Analytics
ga:
    id: Octan3
    # host: your_host
